apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30543  # Ensure it's within the 30000-32767 range
  type: NodePort
